window.FYN_SECTORS = window.FYN_SECTORS || {};
Object.assign(window.FYN_SECTORS, {
ai:{n:'01',kicker:'Supercycle',title:'AI & Compute',sub:'The capex supercycle, the silicon stack, the foundation-model giants and the bubble debate.',momentum:'Mixed',heat:8.5,
 stats:[['2026/FY27 hyperscaler capex','$825–855B','Amazon ~$220B · Alphabet $195–205B · Microsoft ~$190B · Meta $130–145B · Oracle $90–95B. ~32% debt-funded.'],['Anthropic IPO target','$2.0–2.3T','vs OpenAI weighing a $1.2T+ round and pushing its IPO to 2027.'],['H1 2026 global VC','$510B','A record, already above all of 2025. AI took an estimated 70–80%.'],['Reaction to “Pace the Frontier”','Chips ↓ Hyperscalers ↑','Nvidia and chip names sold off Sep 12–14; Meta, Alphabet and Microsoft rose.']],
 tiers:[[1,'Compute & silicon',45],[2,'Hyperscalers',35],[3,'Software & apps',20]],
 watch:[[1,'NVDA','NVIDIA','Core','Q2 FY27 revenue $96.2B (+106%); expects to sell twice the chips next year.','Now exposed to AI-safety rhetoric, not just earnings; the TPU deal signals diversification.'],[1,'AVGO','Broadcom','Core','3.5GW of Google TPU capacity for Anthropic from 2027; AI semis +221% YoY.','A custom-silicon win — and proof Nvidia’s biggest customers are building alternatives.'],[1,'AMD','AMD','Hold','+6.3% on Sep 17 as a neocloud raised pricing; data center revenue +107%.','Consensus target (~$565) barely above price; ROCm vs CUDA unresolved.'],[1,'TSM','TSMC','Core','August revenue +53% YoY; 2026 growth guide “slightly above 40%”.','Capacity squeeze warning to Nvidia and Broadcom; Taiwan remains the tail risk.'],[2,'MSFT','Microsoft','Core','Rose on the “pace” selloff; ~$190B CY26 capex, $80B Azure backlog.','Whether capex is still rewarded once the FY27 ~$255–260B lands.'],[2,'GOOGL','Alphabet','Core','TPUs central to diversification via the Anthropic deal; capex $195–205B.','External TPU commitments vs Gemini’s own compute; open Waymo probes.'],[2,'AMZN','Amazon','Core','~$220B capex; AWS +37% — the clearest payback story.','Whether growth and margins hold into Q3.'],[2,'META','Meta','Hold','Rose with hyperscalers; 7,000 staff moved into Applied AI; capex $130–145B.','Org whiplash adds an execution question to capex discipline.'],[2,'ORCL','Oracle','Watch','Q1 FY27 beat: revenue +30%, OCI +121%; FY27 guide ≥ $90B.','BBB- with a negative outlook; ~$42B FY27 FCF deficit modelled.'],[3,'PLTR','Palantir','Hold','Karp floats nationalizing frontier labs; DA Davidson target $250.','Business quality vs price remains unresolved.'],[3,'PATH','UiPath','Watch','“Pilot to production”; full-year guide ~$1.79B.','13% growth — are agents a tailwind or a replacement for RPA?'],[3,'SPCX','SpaceX','Watch','SpaceXAI cut ~500 annotators; June IPO at $135.','xAI capex $15.8B in Q2 — restructuring or retreat?']],
 privates:[['Anthropic','$2.0–2.3T','IPO target · from $965B','Pre-roadshow meetings underway; $65B run-rate; Nvidia may anchor up to $10B.'],['OpenAI','$1.2T+','Round in talks · from $852B','IPO pushed to 2027; $40B annualized revenue in August.'],['Mistral','$24.4B','Series D · from $13.7B','Record €3B round led by Samsung; Nvidia, ASML and BlackRock in.'],['Waymo','$126B','Valuation','14 cities, 4,000+ vehicles, ~500K paid rides a week; NHTSA probes still open.']],
 bear:[['The revenue gap','$3–4T committed vs ~$50–150B/yr of AI revenue. Cloud’s capex-to-revenue in 2011 was ~2.4:1.',''],['The architects sound the alarm','Amodei, Altman and Hassabis call for a slowdown; Karp floats nationalization.','A ~$2T IPO candidate calling for a pause is also a moat argument.'],['Rates are the transmission','AI debt has added ~0.3pp to 10-year yields; the 30-year sits near 2007 highs.','Oracle’s beat shows demand can still win the argument.'],['Off-balance-sheet leases','~$662B signed but not commenced; Oracle BBB-, FY26 FCF −$23.7B.','Ellison cancelled a planned $7.5B share sale.'],['Circular financing','Nvidia may anchor Anthropic’s IPO, on top of a $105B OpenAI guarantee.','Broadcom TPUs are real, non-Nvidia buildout.'],['The depreciation clock','5–6 year schedules vs a 2–3 year real life could understate D&A by ~$176B.','Secondary pricing says older silicon stays productive.'],['Layoffs while capex soars','128,536 tech layoffs in 2026 through Sep 10 — already above all of 2025.',''],['Concentration everywhere','OpenAI and Anthropic took 40%+ of record H1 VC; a drawdown hits every sector on this hub.','Vendors keep posting record quarters.']],
 catalysts:[['Sep 8','Mistral raises a record €3B Series D','Samsung-led; nearly doubles its valuation to ~$24.4B.'],['Sep 10','Broadcom to supply Anthropic 3.5GW of TPUs','Plus TPU design work through 2031 — the clearest diversification signal yet.'],['Sep 12','Amodei: “pace the frontier”','Chips sold off; hyperscalers rose.'],['Sep 12','Altman rules out a 2026 IPO, floats a $1.2T+ round','~41% above the March mark.'],['Sep 17','Karp: frontier labs may need nationalizing','Calls for developer liability on CNBC.'],['Sep 17','AMD +6.3% on neocloud price hikes','Stifel to $635, Piper to $600.']],
 etfLabel:'YTD',etfs:[['SMH','VanEck Semiconductor','0.35% fee · NVDA/TSM/AVGO heavy',52.9],['AIQ','Global X AI & Tech','Broad stack exposure',20],['QQQ','Invesco Nasdaq-100','0.18% fee · lowest volatility',15.7]],
 srcCount:21,sources:['Fortune','Bloomberg','CNBC','TechCrunch','Tom’s Hardware','Anthropic','Yahoo Finance','The Motley Fool','24/7 Wall St.','GuruFocus','SkillSyncer','PortfoliosLab']},

robotics:{n:'02',kicker:'Physical AI',title:'Robotics',sub:'Humanoids, warehouse automation, surgical systems, defense autonomy and the component supply chain.',momentum:'Bifurcated',heat:7,
 stats:[['Global robotics market, 2026','$38B','+34% YoY — the fastest growth in a decade.'],['Robotics VC, 2026 YTD','~$56B','Roughly double 2025’s full-year record (Dealroom).'],['Unitree market cap','~$30.3B','Down ~54% from its $66B peak; ~125× 2025 revenue.'],['AeroVironment backlog','$1.5B','+37% YoY, 1.4× book-to-bill; shares back to ~$160.']],
 tiers:[[1,'Established',40],[2,'Pure-play automation',25],[3,'Components',25],[4,'Speculative',10]],
 watch:[[1,'NVDA','NVIDIA','Core','Open GR00T N1.6 model, Newton physics and Jetson T4000 (~4× efficiency).','Robotics is still a small slice of a data-center story.'],[1,'ISRG','Intuitive Surgical','Hold','EU approval of da Vinci SP lifted shares to $383.54.','Down ~34% YTD; Ottava and Hugo now real competitors.'],[1,'TER','Teradyne','Core','Gen 7 cobot platform at IMTS; first $100M robotics quarter (+33%).','Pullback risk after a strong product and stock run.'],[1,'6954.T','Fanuc','Hold','Q1 net profit +35%; bounced to ¥5,852.','Still well below the ¥7,334 average target; earnings Oct 22.'],[1,'CAT','Caterpillar','Watch','FieldAI physical-AI partnership formalized Sep 5.','Adoption pace outside mining.'],[1,'ABB','ABB','Watch','Selling Robotics to SoftBank for $5.375B EV.','Regulatory clearance; closing mid-to-late 2026.'],[2,'SYM','Symbotic','Hold','Q3 revenue $721M (+22%), GAAP-profitable, ~$22.6B backlog.','Needham cut to $60 — second cut in two weeks.'],[2,'TSLA','Tesla','Watch','Optimus Gen3; every unit still routed to Tesla’s own factories.','Unscripted factory-work reveal expected Sep/Oct.'],[2,'AVAV','AeroVironment','Core','Q1 FY27 beat; record $1.5B backlog, margins to 40%.','Market catching up — shares ~$160, +14% off the low.'],[2,'KTOS','Kratos','Hold','Valkyrie drone plus a growing laser business; Q2 revenue +30.5%.','$2.08B backlog; no fresh catalyst this week.'],[3,'VPG','Vishay Precision','Core','Target nearly doubled to $77 on a humanoid vendor nomination.','Shares −11% in a month to $60.49; customer concentration.'],[3,'6324.T','Harmonic Drive','Hold','Dominant strain-wave reducers — a humanoid actuator bottleneck.','Order book needs to convert more consistently.'],[3,'CGNX','Cognex','Hold','Raised through-cycle EBITDA target to 25–31%.','Still digesting the HSBC downgrade.'],[4,'SERV','Serve Robotics','Watch','Q2 revenue $3.2M (+404%); 792 daily active robots.','FY26 guide cut to $9–10M from $26M.'],[4,'AGLT*','Agility Robotics','Watch','SPAC at ~$2.5B; $300M+ in Digit orders.','Deal not yet closed — confirm listing status.'],[4,'688836','Unitree','Watch','G1+ launched Sep 15 with six major updates.','FCC import ban and a Chinese bubble warning still in force.']],
 privates:[['Figure AI','~$39B','~$2B raised','Up to 100K Vera Rubin GPUs via Nscale; only ~150 robots shipped in 2025.'],['Skild AI','~$14–15B','$1.4B Series C','S1 foundation model learns tasks from a single video.'],['Physical Intelligence','~$11B+','Round in talks','~$1B raise at nearly double its Series B mark.'],['NEURA Robotics','~$7B','Up to $1.4B Series C','Tether, Qualcomm, Amazon and NVIDIA backing.'],['Apptronik','~$5.5B','$935M+ Series A','Apollo 2 unveiled; demo platform for DeepMind’s VLA model.'],['Boston Dynamics','$3.3B','100% Hyundai-owned','Atlas targeting 30,000 units/yr in Hyundai factories by 2028.']],
 bear:[['Unitree still looks stretched','~125× 2025 revenue even after halving; Beijing’s NDRC warns of a bubble.',''],['Optimus priced out','Polymarket odds of a 2026 commercial launch ~9%, down from ~33%.','An unscripted factory reveal would reset it.'],['Funding outruns revenue','~$56B raised in 2026; Figure’s $39B on ~150 robots shipped.',''],['Demos ≠ autonomy','If a demo isn’t labelled autonomous, assume teleoperation.',''],['Crowding and shakeout','150+ companies chasing humanoids; a reshuffle is widely expected.',''],['Sentiment cuts both ways','AVAV caught up to fundamentals; Symbotic keeps getting cut despite profits.',''],['Revenue is elsewhere','Industrial, logistics and surgical robots earn today; humanoids mostly don’t.','Surgical is a real, contested market.'],['China price war','150+ Chinese humanoid makers compete on price; China ships ~85% of humanoids.','Xi’s visit could soften the FCC ban.']],
 catalysts:[['Sep 20','AeroVironment closes the gap with its beat','~$160, +14% off the post-earnings low.'],['Sep 17','Intuitive gains on EU da Vinci SP approval','Still down ~34% YTD.'],['Sep 15','Vishay Precision target nearly doubles','$77 from $39 on a humanoid vendor nomination.'],['Sep 15','Needham cuts Symbotic again','$60 from $75 despite a profitable quarter.'],['Sep 15','Universal Robots unveils Gen 7 cobots','On top of a first $100M quarter.'],['Sep 24','Xi’s US visit tests the FCC humanoid ban','Beijing calls it damaging to relations.']],
 etfLabel:'Trailing 12m',etfs:[['KOID','KraneShares Humanoid','First humanoid-specific ETF · 50 holdings',56],['ROBO','ROBO Global Robotics','Equal-weight small/mid-cap basket',37],['BOTZ','Global X Robotics & AI','Keyence, Fanuc, ABB heavy',15]],
 srcCount:35,sources:['Bloomberg','Chatham House','CNBC','PBS News','MarketBeat','MedTech Dive','Investing.com','NVIDIA Newsroom','The Robot Report','Fortune','Sacra','U.S. News']},

defense:{n:'03',kicker:'Autonomy',title:'Defense Tech',sub:'AI battlefield software, drones, autonomy and European rearmament.',momentum:'Constructive',heat:5.5,
 stats:[['Global military spending, 2025','~$2.89T','Europe and Canada up ~20% YoY; €800B ReArm Europe runway.'],['Defense-tech VC, 2026 YTD','$35.6B+','Well past 2025’s $9.6B record; rounds at 17–50× revenue.'],['Pentagon FY27 DAWG line','$54.6B','Inside a record $75B drone and counter-drone ask.'],['AVAV LOCUST X3 laser award','$464.8M','The Pentagon’s first directed-energy production contract.']],
 tiers:[[1,'Software & primes',55],[2,'Autonomy pure-plays',45]],
 watch:[[1,'PLTR','Palantir','Hold','UBS lifts its target to $250 — third raise this year; ~$177.','Karp’s nationalization comments; >100× trailing earnings.'],[1,'RHM.DE','Rheinmetall','Core','Recovered to ~€1,020; new USMC unmanned ground vehicle order.','Down ~35% YTD; JPMorgan still at Hold.'],[1,'LHX','L3Harris','Hold','$4.7B Lockheed deal; new CEO and chair settling in.','Kubasik exit unexplained; Golden Dome funding at risk.'],[1,'BA.L','BAE Systems','Core','~11% recovery on a record £84.0B backlog.','Below the 2,360p high; H2 execution unproven.'],[2,'AVAV','AeroVironment','Core','$464.8M laser award on top of the Q1 beat.','SCAR/BADGER class actions still in court.'],[2,'KTOS','Kratos','Trim','Targets climbing after the Q2 beat; consensus $105.62.','Missed the Gauntlet II leaderboard again.'],[2,'RCAT','Red Cat','Avoid','Teal Drones competed in Gauntlet II Close Quarters.','Missed the top five; second negative after insider sales.'],[2,'ONDS','Ondas','Watch','Counter-UAS and loitering-munitions programs continue.','Missed Gauntlet II; Q2 EPS miss; insider sale filing.']],
 privates:[['Anduril','~$100B','In talks · ~9 weeks unclosed','Armed FQ-44 Fury unveiled; IFPC interceptor advances.'],['Helsing','~$18B','$1.8B Series E','Largest defence-tech round in European history.'],['Shield AI','~$12.7B','Series G','Competing for the Navy’s $800M ISR pool with V-BAT.'],['Saronic','~$9.25B','Series D + add-on','Targeting 20+ autonomous ships a year by 2027.']],
 bear:[['Public valuations stretched','A&D index ~32× forward vs ~20× for the S&P 500.',''],['Private marks look bubbly','17–50× revenue rounds; the BIS draws AI-buildout comparisons.',''],['Gauntlet favours private newcomers','Neros, ORQA, XTEND on top; listed pure-plays missed the podium.',''],['Golden Dome can be zeroed','98% of its $17.5B needs reconciliation; a stopgap leaves it with nothing.',''],['Prime governance unresolved','L3Harris has a new CEO and chair; stock 35% off its high.','Contract wins suggest the business is intact.'],['AVAV legal overhang','Class actions over the restatement survive the good news.','']],
 catalysts:[['Sep 19','BAE extends recovery to ~2,043p','Confidence returns to the record backlog.'],['Sep 18','Gauntlet II winners named','Listed pure-plays miss the podium.'],['Sep 17','Karp: AI labs may need nationalizing','A new policy-risk thread for PLTR.'],['Sep 15','UBS lifts Palantir to $250','Demand outpacing capacity after AIPCon 11.'],['Sep 15','Anduril arms the FQ-44 Fury','JDAMs, SDBs and cruise missiles.'],['Sep 9','AeroVironment wins the LOCUST X3 laser contract','Shares +6% on the news.']],
 etfLabel:'Annualized',etfs:[['SHLD','Global X Defense Tech','Palantir and autonomy tilt · since 2023',38],['ITA','iShares US Aerospace & Defense','$13.3B AUM · 0.38% fee · broad US primes',null],['EUAD','Select STOXX Europe Defense','23 holdings · 0.5% fee',null]],
 srcCount:20,sources:['DefenseScoop','Benzinga','DroneXL','GuruFocus','CNBC','The Motley Fool','Army Recognition','TechCrunch','NATO','Fortune','Defense One','Tectonic Defense']}
,
nuclear:{n:'04',kicker:'AI power',title:'Nuclear & SMRs',sub:'Small modular reactors, uranium and the AI power-demand trade.',momentum:'Bifurcated',heat:8,
 stats:[['US grid capex through 2029','~$1T','Hyperscalers hold 13+ nuclear deals totalling ~10 GW.'],['Uranium spot · long-term','$90/lb','Long-term contract hit a record ~$96.50/lb, above 2007’s $95.'],['Constellation six-day slide','−13%','Despite a Q2 beat and raised FY26 guide; MS target $369.'],['Operating commercial SMRs','0','Holtec pulled its IPO; NuScale is the only NRC-approved design.']],
 tiers:[[1,'Operating & cash-generating',65],[2,'Pre-revenue SMR developers',35]],
 watch:[[1,'CEG','Constellation','Core','Largest US fleet (55 GW); Microsoft, Meta, Walmart PPAs.','Six-day 13% slide to ~$255 despite a raised guide.'],[1,'CCJ','Cameco','Core','Major Western uranium producer + 49% of Westinghouse.','Slid to $92.21; avg target $129; Westinghouse IPO pending.'],[1,'BWXT','BWX Technologies','Hold','Backlog +40% YoY; new NNSA design contract.','New 52-week low at $147.52; Investor Day Sep 29.'],[1,'GEV','GE Vernova','Core','+5% on Blue Energy’s Texas BWRX-300 permit filing.','Nuclear is still a small slice of a grid/gas story.'],[2,'OKLO','Oklo','Watch','Q2 revenue $1.2M beat; ~$1.64B cash; Piper $55 target.','~$2B ATM authorized — live dilution overhang.'],[2,'SMR','NuScale','Watch','Only design with full NRC approval.','Slid to $8–9; 6GW TVA/ENTRA1 deal still non-binding.'],[2,'LEU','Centrus','Core','Multi-year HALEU deal with Antares incl. prepayments; +6.6%.','Builds on the $900M DOE Piketon order.']],
 privates:[['TerraPower','Natrium','Gates-backed','Bechtel split on Kemmerer’s next phase; UK power targeted by 2034.'],['X-energy','Public (XE)','Post-IPO','UK design assessment opened; Texas Capital Buy/$22 vs Piper Sell/$9.'],['Kairos Power','500 MW','Google fleet deal','Hermes 2 under construction at Oak Ridge; first unit by 2030.'],['Commonwealth Fusion','$4B raised','SPARC','Cryogenics hit 8K ahead of a 2027 breakeven run.'],['Helion','5GW talks','Microsoft + OpenAI','Polaris hit 150M°C with measurable D-T fusion.'],['Holtec','IPO pulled','Was $10.2B target','$564M trailing revenue; S-1 still on file.']],
 bear:[['Holtec pulled a real business','$564M revenue and an operating asset still couldn’t price a $900M IPO.',''],['TerraPower lost its lead contractor','Bechtel walked from Kemmerer’s next phase.','Both sides say the schedule is unaffected.'],['A slide with no bad news','CEG fell six sessions straight after beating and raising.','Read as cash-flow timing, not a broken thesis.'],['“Closing in” for over a year','NuScale’s 6GW TVA/ENTRA1 deal is still an MOU, not revenue.','']],
 catalysts:[['Sep 18','Holtec pulls its ~$900M IPO','No new pricing date set.'],['Sep 18','Bechtel and TerraPower split on Kemmerer','~200 roles on a WARN notice; most redeployed.'],['Sep 17','Centrus signs HALEU deal with Antares','Prepayments fund Piketon capacity; +6.6%.'],['Sep 16','Blue Energy files Texas SMR permit','GE Vernova +5%.'],['Sep 15','UK opens Xe-100 design assessment','Three-year review behind a 6 GW plan.'],['Sep 29','BWXT Investor Day','Management makes its growth case after a 52-week low.']],
 etfLabel:'1 week',etfs:[['URNM','Sprott Uranium Miners','Pure miners · higher beta',2.9],['URA','Global X Uranium','Miners + fuel cycle · $41.65',-2.4],['NLR','VanEck Uranium & Nuclear','Utilities + miners + SMRs · $107.69',-2.6]],
 srcCount:10,sources:['Barron’s','Reuters','Construction Dive','World Nuclear News','The Motley Fool','Centrica','Trefis','Business Wire','Carbon Credits']},

minerals:{n:'05',kicker:'Sovereignty',title:'Critical Minerals',sub:'Rare earths, lithium and the Western supply-chain onshoring trade.',momentum:'Crosscurrents',heat:4,
 stats:[['MP Materials, Sep 18','−4.3%','Beijing’s group moves on Shenghe, MP’s 3% Chinese holder.'],['Until Xi’s Washington visit','3 days','Rare-earth licensing on the agenda; 47 days to the Nov 10 expiry.'],['Lithium carbonate','$19,750/t','Down a further 0.8% w/w — a decline running all year.'],['Freeport recovers','$71.50','Back above $100B after the tariff-doubt plunge.']],
 tiers:[[1,'Established producers',65],[2,'Developers & small caps',35]],
 watch:[[1,'MP','MP Materials','Core','Only US mine + processing; Q2 revenue doubled to $126.1M.','New Beijing-consolidation overhang; magnets guided for Q4.'],[1,'LYC.AX','Lynas','Hold','Largest non-China producer; record FY26 profit.','CEO search 2+ months; transition support ends Sep 30.'],[1,'ALB','Albemarle','Hold','Atacama guide of 70,700t LCE intact.','Mizuho cut to $140; new CEO not until Feb 2027.'],[1,'FCX','Freeport-McMoRan','Core','Recovered to ~$71.50 after a 7–8% tariff plunge.','Section 232 copper tariff still unresolved.'],[2,'USAR','USA Rare Earth','Watch','Broke ground on a South Carolina magnet plant.','Fresh offering filed; −54% from peak; new CEO Oct 1.'],[2,'UUUU','Energy Fuels','Core','Pilot Dy oxide at 99.9% — ahead of automotive spec.','VAC acquisition closing Q1 2027.'],[2,'LAC','Lithium Americas','Hold','Thacker Pass on track for Q4 2026 energization.','Mechanical completion late 2027 into a soft lithium price.']],
 privates:[],
 bear:[['Commodity cycles cut both ways','Lithium keeps sliding; NdPr fell as a block for the first time since May.',''],['China can flood, freeze or consolidate','Shipments still withheld while Beijing moves on Shenghe.',''],['Policy tailwinds aren’t guaranteed','Freeport’s plunge shows how much rests on unfinalized tariffs.','Real support exists — each dollar still has to land.'],['Dilution and leadership overhangs','USAR offering, Lynas CEO gap, Albemarle CEO in 2027.','None disqualifying on its own.']],
 catalysts:[['Sep 9','USA Rare Earth breaks ground in South Carolina','Real build-out amid dilution worries.'],['Sep 10–11','Copper miners tumble on tariff doubt','FCX −8%, then recovers.'],['Sep 18','China Rare Earth Group eyes Shenghe','An indirect window into MP.'],['Sep 19','Mizuho cuts Albemarle to $140','Lithium slips to $19,750/t.'],['Sep 24–25','Xi Jinping in Washington','Rare-earth licensing and shipment halts on the table.']],
 etfLabel:'Trailing 12m',etfs:[['REMX','VanEck Rare Earth & Strategic Metals','~$70–73 · ranging ahead of the summit',43],['LIT','Global X Lithium & Battery','~$70.50 · tracking lithium’s slide',null],['XME','SPDR Metals & Mining','~$108.68 · broad US metals',null]],
 srcCount:18,sources:['Reuters','MINING.COM','TS2 Tech','Benzinga','Kalkine','Rio Times','24/7 Wall St.','Benchmark Mineral','The Motley Fool','Energy Fuels IR','EXIM']}
,
space:{n:'06',kicker:'Frontier',title:'Space Economy',sub:'Launch, satellites, constellations and the post-SpaceX-IPO landscape.',momentum:'Most active',heat:7.5,
 stats:[['Space economy by 2035','$1.8T','~$626B in 2026 (McKinsey, Goldman Sachs).'],['SPCX below post-IPO high','~32%','~$152.71 vs a $225.64 high; Starship 14 now NET Sep 28.'],['Space startup funding, 2026 YTD','$20.3B','A record with a quarter still to go; US ~63%.'],['Rocket Lab Iridium financing','$1.94B','ATM completed; $3.6B bridge cancelled. Neutron still 2027.']],
 tiers:[[1,'Scale players',60],[2,'Growth / speculative',40]],
 watch:[[1,'SPCX','SpaceX','Core','Q2 revenue $7.8B (+92%); Starlink 12M subs, ~$17B annualized.','Starship 14 slipped again; four unlock tranches through Dec 8.'],[1,'RKLB','Rocket Lab','Core','Iridium fully funded; 96th Electron flight; Craig-Hallum Buy.','Well off 2026 highs; Neutron maiden flight pointed at 2027.'],[1,'LHX','L3Harris','Hold','Guggenheim Buy with 49% upside; space segment $13B+.','Near 52-week lows; also in the Defense sleeve — don’t double-count.'],[2,'ASTS','AST SpaceMobile','Watch','BlueBirds 12–13 deployed; US Mobile Q4 direct-to-cell launch.','−10% on the news; class action pending; wider Q2 loss.'],[2,'LUNR','Intuitive Machines','Watch','SXM-11 handover done; new IM 300 order; $1.8B backlog.','$259M net insider selling in 12 months.'],[2,'PL','Planet Labs','Trim','First profitable quarter; Q2 revenue +58%.','−67% from its May peak on a proposed $1.5B raise.'],[2,'RDW','Redwire','Trim','Record Q2 revenue $117.1M (+90%) and $542M backlog.','$1.15B net insider selling; −7% on Sep 18.']],
 privates:[['Blue Origin','Bezos-funded','New Glenn return','NASA calls it “Plan A” for this year; SpaceX veterans doubt it.'],['Firefly','NASDAQ: FLY','$981M Space Force IDIQ','Roth Buy, Morgan Stanley Hold; −53% over 12 months.'],['Stoke Space','~$10B','$1B Series E','Nova Block 2 (15t reusable) targeted for 2029.']],
 bear:[['Capital intensity','Rocket Lab’s $1.94B dilutive ATM; Stoke’s Block 2 not until 2029.',''],['Government concentration','SHIELD IDIQ now 2,400+ vendors, diluting any single edge.','L3Harris keeps winning big contracts.'],['SpaceX absorbs the value','A launch-cost incumbent compresses everyone else’s margins.',''],['Binary mission risk','Starship 14 slipped three times in three weeks; Neutron to 2027.','']],
 catalysts:[['Sep 19','Rocket Lab flies its 96th Electron','17th mission of 2026.'],['Sep 18','Redwire −7% on insider-selling disclosure','Despite a BofA target hike.'],['Sep 16','L3Harris at Morgan Stanley Laguna','A day after Guggenheim’s Buy.'],['Sep 15','Rocket Lab fully funds Iridium','$3.6B bridge cancelled.'],['Sep 10','ASTS deployment news meets a sell-off','−10% on BlueBirds 12–13.'],['Sep 28','Starship Flight 14 (NET)','First true orbital attempt, 26 Starlink V3.']],
 etfLabel:'YTD',etfs:[['UFO','Procure Space','Revenue-weighted pure-play',47],['ROKT','SPDR Kensho Final Frontiers','Space + defense + deep-sea',52],['ARKX','ARK Space Exploration','Active, tech-adjacent',22]],
 srcCount:21,sources:['GlobeNewswire','Seeking Alpha','GuruFocus','Yahoo Finance','The Motley Fool','SpaceWatch.Global','Breaking Defense','Crunchbase News','TechTimes','Spaceflight Now']},

storage:{n:'07',kicker:'Grid',title:'Energy Storage',sub:'Grid-scale batteries, the storage software layer and next-gen chemistry.',momentum:'Mixed',heat:5,
 stats:[['US battery storage','52 → 64.9 GW','Record 24 GW of 2026 additions; 89 GW pipelined for 2027.'],['Fluence FY26 guide','$2.4B','Cut from ~$3.0B; EBITDA to a ~$200M loss; SEC probe.'],['GE Vernova backlog','$176B','CEO sees $200B “very early” 2027; shares −14% in a month.'],['Eos DOE loan advance','$87M','Funds Thorn Hill line two; shares $3.04 → $4.08.']],
 tiers:[[1,'Scale / revenue',65],[2,'Next-gen / speculative',35]],
 watch:[[1,'TSLA','Tesla Energy','Core','Megablock flagship; Brookshire Megafactory on track for H2 2026.','Q3 print tests the 31.4% energy margin.'],[1,'FLNC','Fluence','Avoid','Still a large global backlog.','Guide slashed, SEC probe, −15.4% in a day, five law firms.'],[1,'GEV','GE Vernova','Core','Backlog $176B (+37%); $200B early 2027.','Sector derating so far; October print next.'],[1,'ENPH','Enphase','Hold','Bidirectional EV charging and IQ Battery C80.','−3.8% on the Fed hike; Hold consensus, ~$45 target.'],[2,'QS','QuantumScape','Watch','Cobra cells shipping for B1 sampling; PowerCo launch 2027.','−51% YTD; CTO share sales; CATL/BYD 2027 targets.'],[2,'EOSE','Eos Energy','Core','Google/MN8 10MW/100MWh Z3 deal; DOE advance.','Revenue from the deal not until 2028–2030.'],[2,'STEM','Stem','Watch','Fifth straight positive adjusted EBITDA quarter.','Near its 52-week low; earnings Oct 29.'],[2,'NRGV','Energy Vault','Trim','275MW Rolls-Royce generation financing closed.','~−40% EBIT margin; ~−$40M quarterly FCF.']],
 privates:[],
 bear:[['China dominates cells','CATL + BYD now 62.4% of installations; CATL locks a 200GWh deal.',''],['Tariffs and FEOC rules','Section 301 on Chinese ESS batteries up to 58.4%; 55% domestic content in 2026.',''],['Fluence taints the stack','Stem’s slide shows execution risk priced across the software layer.',''],['Solid-state keeps slipping','No QuantumScape production license yet; China targets 2027 trials.','']],
 catalysts:[['Sep 9','DIMAAG-AI and Toshiba partner on data-center storage','Lithium-titanate cells, 10C, 10+ year life.'],['Sep 14','Fluence names Bernerd Da Santos COO','Two days before the guidance cut.'],['Sep 16','Fluence slashes FY26 guide, discloses SEC probe','Houston manufacturing delays.'],['Sep 16','GE Vernova CEO: $200B backlog early 2027','Strong Q3 order intake.'],['Sep 17','Fluence −15.4% as law firms circle','$9.05 → $7.66.'],['Sep 18','Solar/storage fall on the Fed hike','Energy Vault bucks it, +5.2%.']],
 etfLabel:'Price',etfs:[['GRID','First Trust Smart Grid','$176–178 · flat on the week',null],['BATT','Amplify Lithium & Battery','~$13.96 · $9.67–18.08 range',null],['LIT','Global X Lithium & Battery','~$74.18 · tracks EV complex',null]],
 srcCount:18,sources:['Energy-Storage.News','GlobeNewswire','StockTitan','24/7 Wall St.','The Motley Fool','StocksToTrade','Canary Media','ESS-News','SCMP','Battery-Tech Network','Yahoo Finance']}
,
biotech:{n:'08',kicker:'Comp bio',title:'AI Biotech',sub:'AI-native drug discovery, the multiomics stack, longevity capital and the ARKG lens.',momentum:'Constructive',heat:6,
 stats:[['Intellia lonvo-z PDUFA','Mar 10, 2027','Would be the first in-vivo CRISPR approval; HAELO Phase 3 cut attacks 87%.'],['Illumina rejoins the S&P 500','Sep 21','First time since 2023; 52-week high $239.55, +143% over 12 months.'],['Tempus AI one-week surge','+40%','100K-genome platform + ARPA-H award; now ARKG’s #2 holding.'],['ARKG AUM','$1.93B','Down from $2.00B even as price hit a 52-week high — redemptions into strength.']],
 tiers:[[1,'Established / hedged',40],[2,'AI-native platforms',30],[3,'Tooling & diagnostics',30]],
 watch:[[1,'LLY','Eli Lilly','Core','Isomorphic + $2.75B Insilico deal; $1B NVIDIA AI lab.','Merida close in Q4; VERVE-102 Phase 2 by year-end.'],[1,'NVS','Novartis','Core','Isomorphic renewed; Chai and Relation deals.','Q2 sales +3%; multi-partner AI bet compounding.'],[1,'NVDA','NVIDIA','Hold','BioNeMo compute layer; Lilly co-innovation lab.','Quietly widening the compute moat.'],[2,'RXRX','Recursion','Watch','Rebounded to ~$3.71 on early REC-7735 data.','Still dose-finding — sentiment repair, not efficacy.'],[2,'SDGR','Schrödinger','Hold','Launched Bunsen, an agentic AI co-scientist.','No new SGR-1505/3515 clinical data.'],[2,'RLAY','Relay','Watch','Zovegalisib advancing; two conferences in nine days.','~$463M ATM overhang before the 2027 Phase 3.'],[2,'GENB','Generate Bio','Hold','Generative protein design; $1B Novartis deal.','Above the $16 IPO but off its $20.38 high.'],[2,'EIKN','Eikon','Avoid','Live-cell single-molecule tracking; $381M IPO.','Below IPO price; board resignations; no catalyst.'],[3,'ILMN','Illumina','Core','Back in the S&P 500; UBS Buy, target $260.','Seven analysts raised FY26 EPS in 60 days.'],[3,'TEM','Tempus AI','Hold','~40% weekly surge on the genome platform.','Guardant litigation unchanged.'],[3,'GH','Guardant','Watch','ARKG weight up to #6.','$245.2M TwinStrand appeal pending.'],[3,'QSI','Quantum-Si','Core','Detected 18 of 20 amino acids on Proteus.','Launch still delayed to Q2 2027.']],
 privates:[['Isomorphic Labs','$2.1B','Series B · Alphabet','“Not slowing down”; first trials targeted by year-end.'],['Insilico','$2.75B + $2.5B','Lilly + SK deals','Rentosertib approval now 2029–30, not 2027–28.'],['Xaira','~$1.3B raised','$1B+ launch round','X-Cell virtual cell model; no trial started yet.'],['NewLimit','$3.1B','$435M Series C','~71% of this year’s disclosed longevity funding.']],
 bear:[['Biology still fails in the clinic','Zero AI-discovered drugs approved out of 200+ in trials.',''],['Diagnostics litigation mess','Three live lawsuits between Guardant and Tempus.',''],['Sentiment outruns biology','Tempus +40% and Recursion +9% on thin catalysts.','Cuts both ways.'],['Funds shrink while price rallies','ARKG AUM fell as price hit a 52-week high.',''],['M&A pace is a valuation risk','Deal size +44% y/y to $527M as pharma refills a $300B patent cliff.','']],
 catalysts:[['Sep 21','Illumina rejoins the S&P 500','Index buying on top of a real turnaround.'],['Sep 15–18','Tempus AI surges ~40%','100K-genome platform + ARPA-H cardiology award.'],['Sep 15','Quantum-Si reads 18 of 20 amino acids','Toward all 20 in 2026.'],['Sep 15–16','Morgan Stanley Healthcare Conference','Recursion, Tempus, Intellia, Relay, Schrödinger.'],['Recent','Intellia gets a Mar 10, 2027 PDUFA','Plus a $400M credit facility.'],['Aug 27','Guardant’s suit against Tempus proceeds','Litigation runs both ways.']],
 etfLabel:'YTD',etfs:[['ARKG','ARK Genomic Revolution','Active · 33 holdings · 0.75%',63.3],['XBI','SPDR S&P Biotech','Equal-weight · 0.35%',34.8],['IBB','iShares Biotechnology','Cap-weighted · 0.44%',28.7]],
 srcCount:37,sources:['MarketBeat','TipRanks','Yahoo Finance','StocksToTrade','CourtListener','Law360','GlobeNewswire','StockAnalysis','ARK Funds','Semafor','STAT News','CNBC','BioPharma Dive']},

quantum:{n:'09',kicker:'Deep tech',title:'Quantum',sub:'Pure-plays, hedged giants and the road to commercial advantage.',momentum:'Extreme spec',heat:9.5,
 stats:[['Quantum market by 2035','$97B','Projected; most systems still in R&D.'],['Broad rally, Sep 12–18','+1.8% to +10.7%','Every major name up; QTUM ETF −3.2% on tech rotation.'],['September CHIPS quantum total','$1.4B','IBM’s Anderon $1B (matched) + $400M to four pure-plays.'],['Pure-play price-to-sales','64–514×','IonQ ~64× · Rigetti ~401× · D-Wave ~514×.']],
 tiers:[[1,'Hedged giants',60],[2,'Pure-plays',40]],
 watch:[[1,'IBM','IBM','Core','Anderon finalizes a $1B CHIPS award for its Albany foundry.','Yield ramp on the 300mm line.'],[1,'GOOGL','Alphabet','Trim','UK NQCC opens access to the 105-qubit Willow chip.','A fifth quiet week for hardware milestones.'],[1,'MSFT','Microsoft','Hold','Quantinuum partnership compounding; +10.7% for QNT.','Majorana reproducibility.'],[1,'NVDA','NVIDIA','Core','CUDA-Q Logical: Fermilab 7× faster; NVQLink live.','Adoption across labs; QuEra investment terms.'],[2,'IONQ','IonQ','Hold','Four IEEE Best Paper awards; +6.5% to $39.13.','Cheapest pure-play at ~64× sales.'],[2,'RGTI','Rigetti','Trim','Q2 revenue $5.1M (+185%); $100M CHIPS award.','Confirmed out of DARPA QBI Stage B.'],[2,'QBTS','D-Wave','Watch','Second NTT DOCOMO production app; BMO Outperform.','Q2 revenue missed by ~25%; four law firms.'],[2,'PSQL','Pasqal','Watch','Neutral atoms; Nasdaq since Aug 28, ~$360M cash.','~$7.94 vs a $19.11 debut close.']],
 privates:[['PsiQuantum','~$10.5B','$1.5B round','Photonic; Moreton Bay facility under way.'],['Quantinuum','~$14.3B','Public (QNT)','Stage B participant; FY26 revenue guide just $28–32M.'],['QuEra','$230M+','Google, SoftBank, NVentures','96 logical qubits; advanced to QBI Stage B.']],
 bear:[['Years from commercial advantage','Revenue is mostly government, research access and pilots.',''],['A rally doesn’t erase execution','D-Wave rose despite a 25% miss; Rigetti rose despite the DARPA exclusion.',''],['Insiders keep selling','~$988M net sold at IonQ, Rigetti and D-Wave over five years.',''],['Dilution as a business model','Quantinuum at ~$14.3B on $28–32M of revenue.',''],['The winner may not be listed','Anderon is an IBM subsidiary; PsiQuantum and QuEra are private.','']],
 catalysts:[['Sep 21','FIPS 140-2 sunset takes effect','Only 140-3 accepted for new federal procurement.'],['Sep 18','D-Wave’s Q2 miss draws legal scrutiny','Revenue $3.08M vs ~$4.05M expected.'],['Sep 17','IonQ and Synopsys win IEEE Best Paper','CAE workflows up to 14.6% faster.'],['Sep 16','IBM’s Anderon finalizes its $1B CHIPS award','Largest quantum award to date.'],['Sep 14','NVIDIA launches CUDA-Q Logical','Fermilab 5 months → 3 weeks.'],['Sep 23–25','Quantum World Congress','Quantinuum and D-Wave presenting.']],
 etfLabel:'Price',etfs:[['QTUM','Defiance Quantum','$142.74 · 52-week high $170',null],['SMH','VanEck Semiconductor','Indirect: the substrate quantum must beat',null]],
 srcCount:10,sources:['IBM Newsroom','NVIDIA Newsroom','The Quantum Insider','IonQ','StocksToTrade','DARPA','Federal News Network','The Motley Fool']}
});

// Weekly Brief data — updated each Monday by the research pipeline
window.FYN_BRIEF = {
  strip:[
    ['S&P 500','5,738','+0.21%'],
    ['Nasdaq','18,210','+0.40%'],
    ['VIX','16.2','−3.1%'],
    ['US 10Y','4.18%','−0.02'],
    ['BTC','$112,480','+1.12%'],
    ['ETH','$4,182','+0.86%'],
    ['Fed funds','3.75–4.00%','Held']
  ],
  // [id, name, tag, raised[], cut[], story, check]
  sect:[
    ['ai','AI & Compute','Mixed',[],[],'Amodei’s “Pace the Frontier” essay sank chips and lifted hyperscalers; Broadcom’s 3.5GW TPU deal for Anthropic diversifies compute away from Nvidia.','$3–4T committed against ~$50–150B/yr of AI revenue is still the central tension. Oracle’s beat keeps the demand case intact.'],
    ['robotics','Robotics','Bifurcated',['VPG','J&J Ottava'],[],'Vishay Precision’s target nearly doubles on a humanoid vendor nomination; J&J’s Ottava earns a speculative starter.','Symbotic cut again despite a profitable $721M quarter; Unitree still ~54% below its August peak.'],
    ['defense','Defense Tech','Constructive',['AVAV','BAE'],['KTOS','RCAT → Avoid'],'AeroVironment wins the Pentagon’s first directed-energy production contract ($464.8M); BAE’s backlog hits a record £84B.','Kratos and Red Cat miss Gauntlet II; Karp’s call to nationalize AI labs adds regulatory risk.'],
    ['nuclear','Nuclear & SMRs','Bifurcated',['LEU'],[],'Centrus signs the first dated commercial HALEU contract; UK opens a design review of X-energy’s Xe-100.','Holtec pulls its ~$900M IPO — a revenue-generating operator stepping back is the reality check on SMR enthusiasm.'],
    ['minerals','Critical Minerals','Crosscurrents',['UUUU'],[],'Xi’s first White House visit in 11 years puts rare-earth licensing on the table, 47 days before the Nov 10 expiry.','MP −4.3% as Beijing moves on its Chinese shareholder; lithium slides to $19,750/t.'],
    ['space','Space Economy','Most active',['RKLB','LHX','ASTS','LUNR'],['RDW','PL'],'Rocket Lab fully funds Iridium; L3Harris gets a Buy initiation with 49% upside. Six of eight names moved.','Redwire hit by insider selling; Planet Labs −67% from peak on a dilutive raise. Starship 14 slips to Sep 28.'],
    ['storage','Energy Storage','Mixed',['EOSE'],['NRGV'],'Eos firms a 10MW/100MWh Google contract; an $87M DOE advance funds its second line.','Fluence cuts its FY26 guide to ~$2.4B, discloses an SEC probe and falls 15.4% in a session.'],
    ['biotech','AI Biotech','Constructive',['ILMN','NTLA','QSI'],[],'Illumina rejoins the S&P 500; Intellia gets a firm Mar 10, 2027 PDUFA; Quantum-Si reads 18 of 20 amino acids.','Tempus +40% on a platform announcement with no clinical event; still zero AI-discovered drugs FDA-approved.'],
    ['quantum','Quantum','Extreme spec',['IBM','NVDA','IONQ'],['GOOGL','RGTI','Quantinuum'],'IBM’s Anderon lands the largest quantum CHIPS award yet ($1B, matched); NVIDIA’s busiest quantum week in a month.','Every pure-play rallied, yet Rigetti (missed DARPA Stage B) and Quantinuum were trimmed on valuation.']
  ],
  // valuation heat scores 0-10
  heat:{ai:8.5,robotics:7,defense:5.5,nuclear:8,minerals:4,space:7.5,storage:5,biotech:6,quantum:9.5},
  // [kicker, headline, body]
  themes:[
    ['AI slowdown','A safety essay moved more than a week of earnings','Amodei’s Sept 12 essay, backed by Altman and Hassabis, sent chips lower and hyperscalers higher. Skeptics: a ~$2T IPO candidate asking rivals to slow down is also a moat argument.'],
    ['Upgrades','Every raise this week had a proof point behind it','17 names raised across seven sectors — each on a converting contract, a regulatory step or a partner-validated milestone, not a story alone.'],
    ['Downgrades','Cuts share a missed proof point, not a scandal','Missed leaderboards, insider selling, a confirmed DARPA exclusion, or a market cap outrunning unchanged guidance.'],
    ['Speculation repricing','Holtec pulls a $900M IPO from a real business','A $564M-revenue operator stepping back — with Unitree −54% and Planet −67% from peaks — is the clearest tell 2026’s froth is still repricing.'],
    ['Policy as price-setter','Washington and Beijing keep setting the terms','IBM’s $1B CHIPS award, the Pentagon’s first laser production contract and Xi’s visit moved prices more than any single earnings print.']
  ],
  // [date, sector-tag, headline, summary]
  news:[
    ['Sep 12','AI','Amodei calls for the industry to “pace the frontier”','Backed by Altman and Hassabis; chips sold off while Meta, Alphabet and Microsoft rose.'],
    ['Sep 16–18','Nuclear','Holtec pulls its ~$900M Nasdaq IPO','“Market conditions,” days after targeting a $10.2B valuation — despite $564M of trailing revenue.'],
    ['Sep 16','Quantum','IBM’s Anderon finalizes a $1B CHIPS Act award','Matched by $1B from IBM; September’s federal quantum commitment reaches ~$1.4B.'],
    ['Sep 18','Minerals','MP Materials −4.3% as Beijing moves on its shareholder','China Rare Earth Group in talks to acquire Shenghe, days before Xi’s White House visit.'],
    ['Sep 9','Defense','AeroVironment wins the first directed-energy production contract','$464.8M for LOCUST X3 lasers on top of a Q1 beat; shares back toward $160.']
  ],
  // [date, headline, body, accent?]
  ahead:[
    ['Sep 22','Richmond Fed & 2-yr auction','First data since the Sept 16 hike to 3.75–4%.',false],
    ['Sep 23','Flash PMIs','First broad read on the post-hike economy.',false],
    ['Sep 24–25','Xi in Washington','Rare-earth licensing on the agenda.',true],
    ['Sep 25','Micron earnings','The week’s key AI supply-chain print.',true],
    ['Sep 28','Starship Flight 14','Slipped three times in three weeks.',false],
    ['~Sep 30','Anduril’s ~$100B round','Markets floating a $112.5B close.',false],
    ['Oct','Anthropic IPO pricing','~$2.0–2.3T target, before the midterms.',false]
  ]
};
